### ISSUE TITLE
micropython.uf2 is lagging behind.

### ISSUE THREAD

**Issue by beetlegigg** [pimoroni/yukon#13]
Micropython has had several releases since your pimoroni-yukon-v1.0.1-micropython.uf2 release.  Please can you inform if you are going to produce a more up to date release.   Thank you.
Also can you inform if its possible to use one of the micropython standard releases, perhaps the one for the rpi pico instead of the Pimoroni one?

**Comment by Gadgetoid** [comment]
You cannot use the MicroPython standard releases, Yukon's firmware is customized to avoid any spicy runaway robot problems.

For this same reason, we're not quick to adopt changes since those changes need migrated across.

Is there a specific feature or fix which you're needing from a more recent version of MicroPython?

For posterity, the full diff between our MicroPython and the latest release is:

https://github.com/micropython/micropython/compare/b88262ce96c3433a02b2c8d984ba01e071b60c1f...v1.22.2

And the changes to the bleeding edge version:

https://github.com/micropython/micropython/compare/b88262ce96c3433a02b2c8d984ba01e071b60c1f...master

At this point there are enough in-progress commits that we'll probably wait for an official v1.23 release.

**Comment by Gadgetoid** [comment]
@ZodiusInfuser tells me there are some more recent builds here:

https://github.com/pimoroni/yukon/actions/runs/8897562982

Based on a branch building against a slightly updated version of our MicroPython fork here:

https://github.com/pimoroni/yukon/tree/ci/micropython-edge

Which gets us this far from v1.22.2 - https://github.com/micropython/micropython/compare/ae6c33a1dda01d5b36b8f5c9e8e0bd3425ba796a...v1.22.2

**Comment by ZodiusInfuser** [comment]
Thanks for replying to this @Gadgetoid!

@beetlegigg I've done some initial tests of that build, but would welcome more eyes on it to catch any mistakes I may have made in the upgrade process.
